### ISSUE TITLE
Week 2 - 2과제에서 데이터 관련 질문입니다.

### ISSUE THREAD

**Issue by jong6598** [walking-sunset/wanted-pre-onboarding-qna-7th#10]
1. 데이터를 따로 주셨는데, 실제 url에 api 요청을 해서 데이터를 받는 것이 아니라 저 데이터를 더미데이터로 사용해서 구현을 하면 되는걸까요?

2. `임의적으로 Fetch 타임을 만들어 로딩 시간 지연` 이라는 요구사항에서, setTimeout 등을 이용해서 데이터 페칭 하는 시간 딜레이를 만들라는 의미일까요? 

3. 제공된 데이터에는 매체현황 관련된 데이터가 있던데 요구사항에서는 `매체현황은 구현 X` 이렇게 적혀있어서, 매체현황을 제외한 통합광고현황 부분만 구현하면 되는걸까요??

**Comment by ryong9rrr** [comment]
안녕하세요 저는 수강생입니다..! 아까 연욱님께서 과제 설명하시면서 말씀하셨던 부분이라 제가 답변드릴 수도 있을 것 같아서 댓글 답니다!
1. 정확히 맞습니다.
2. 이 부분은 과제 요구 사항이라 자세히 설명해주시지는 않았지만 SetTimeout과 Promise 객체를 이용해서 비동기 함수처럼 연출할 수 있습니다. 저희 조는 그렇게 하고 있습니다.
3. 넵! 매체현황 박스는 제외해도 된다고 하셨습니다!

**Comment by jong6598** [comment]
너무 감사합니다! 화이팅하세요~

**Comment by YeonghunKO** [comment]
저희 조 같은 경우 2번은 json-server를 이용해서 데이터를 불러오고 있습니다. firebase와 mongodb도 생각해봤는데 learning curve가 가장 완만한 json-server를 선택하였네요

**Comment by walking-sunset** [comment]
👍
