### ISSUE TITLE
HTTP 캐싱 관련 질문입니다.

### ISSUE THREAD

**Issue by movie42** [walking-sunset/wanted-pre-onboarding-qna-7th#11]
이건 과제 요구 조건과 관계가 없는 질문입니다. 하지만 궁금한 부분이라 질문을 드립니다. 

과제는 jsonserver인데 get 요청은 기본적으로 http 캐싱이 되는 것으로 보입니다.(서버에 요청시 304를 반환합니다.)

그런데 네트워크 창은 status 코드가 200이고 로컬 캐시 데이터로 부터 데이터를 가져왔다는 메시지가 보이지 않는데요. 

이런 경우는 
1. 프론트에서 http 요청을 보낼 때 headers에 "Cache-Control" 정보를 함께 보내줘야 되는 것인지 
2. 아니면 캐싱은 되고 있는데 그냥 네트워크에 정보가 누락된 것인지 
3. 마지막으로 그것도 아니면 서버에서 캐시에 대한 세부 사항이 누락되었기 때문인지
궁금합니다.

**Comment by movie42** [comment]
<img width="1878" alt="스크린샷 2022-11-09 오후 11 47 23" src="https://user-images.githubusercontent.com/44064122/200862856-40a592c6-e73f-4f4e-8d8c-8b8a9793b6f8.png">

캐싱이 되는 것 같은 증거는 있는데 From memory disk와 같은 메시지가 없어서 캐싱이 되고 있는지 확신이 들지 않습니다. 

![캐싱](https://static.toss.im/assets/toss-tech/smart-web-service-cache-1.png)

1. 그래서 혹시 클라이언트에서 HTTP 요청을 보낼 때, 헤더에 Cache-Control과 같은 옵션을 함께 보내줘야하는 것인지.
2. 아니면 캐싱이 잘 되고 있는데 그냥 UI 누락인 것인지
3. 아니면 애초에 서버에서만 컨트롤이 가능한데 캐싱 옵션이 조정되어있지 않은 것인지

궁금합니다.

**Comment by starkoora** [comment]
@movie42 좋은 질문이네요 :)
저도 확인해보고 흠칫해서 여러모로 좀 찾아 봤는데 이해가 좀 되는 것 같아 정리해서 답변을 드립니다.

결론부터 말씀드리자면 현재 브라우저 캐시를 사용하고 있는 상태일겁니다. 브라우저에서 개발자 도구를 켜고 강력 새로고침을 한 뒤 요청을 보내보시면 서버 측에서 200이 뜨는데, 다시 한번 요청을 보내보시면 304가 뜰겁니다.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/109899564/200900602-0eae83d9-859b-4dc9-90e6-fcbb22c60bc0.png">

다만, 서버에서 304를 내려주더라도 브라우저에서 200으로 표기하는 경우가 더러 있는 듯 합니다.
우리가 살펴볼 수 있는 경우 중에서는 아래와 같은 케이스가 있는 것 같고, 지금 질문 주신 경우는 2번에 해당하겠네요.
- 브라우저 memory, disk cache가 된 경우
- 같은 도메인 / 포트가 아닌 곳에서 온 응답인 경우
- cachable 하지 않은 http method를 사용했을 경우 (ex. POST)
- ...

https://stackoverflow.com/questions/61584984/chrome-shows-200-ok-status-in-network-even-if-server-returns-304
이 링크를 보면 같은 도메인 / 포트의 경우 304를 표시하고 있지만, 그렇지 않은 경우 같은 요청이라도 200을 표시하고 있다고 합니다.

실제로 테스트해보면 그러합니다. 전자의 케이스를 테스트 해보려면 주소창에 api 주소를 직접 넣으면되고, (응답이 document로 오는 것에 주목)

<img width="247" alt="image" src="https://user-images.githubusercontent.com/109899564/200900973-9bd32020-564a-4614-920f-5b77f755d76b.png">

<img width="848" alt="image" src="https://user-images.githubusercontent.com/109899564/200900917-1f6457a4-12b9-469a-bc7f-7eb2dbb24b3b.png">

후자를 테스트하려면 프론트 서버를 띄운뒤 거기서 요청을 보내보면 됩니다.

<img width="178" alt="image" src="https://user-images.githubusercontent.com/109899564/200901055-9440c95e-ac42-4865-b79b-d1d867a26bd5.png">

<img width="507" alt="image" src="https://user-images.githubusercontent.com/109899564/200901082-120f3d79-1609-450a-b2a4-2ad12bc57be5.png">

이렇게 도메인이 다른 요청에 대해서 200으로 처리하는 이유를 추측해보자면 300번대 요청은 redirection 의미를 갖는데, localhost:3000에서 localhost:4000으로 리다이렉트 하는 것이 애초에 보안적으로 말이 안되기 때문 아닌가 싶네요. 이건 그냥 혼자 생각해본 추측이니 더 정확한 답변이 있으면 대댓글로 답변 추가 부탁드립니다.

추가로, 잘 살펴보면 찐 200과 짭 200 사이에 응답 size가 차이가 나는 것을 볼 수 있는데, 이 차이가 약 430바이트 정도입니다. 첫 번째 응답은 서버로부터 값을 전부 받아오니 응답 size가 크고, 두 번째 캐싱된 응답을 받아서 쓸 때는 헤더 값만 받아오므로 첫 요청보다는 응답이 작겠죠.

제가 직접 응답 body의 바이트 수를 체크해봤을 때는 280바이트 였고, 나머지 150바이트 정도는 body 문자열에 이스케이프 문자열이나 인코딩 과정들을 통해 길어지면서 생긴 오차가 아닐까 싶습니다.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/109899564/200901207-d39c5867-eb02-4366-a291-713536dbf30f.png">

**Comment by movie42** [comment]
답변 감사합니다. 첫번째 동작은 해봤는데 강력 새로고침을 해도 304를 출력하는데 아마 이건 다른 문제 인것 같네요 서버를 껐다 켜도 똑같이 304라 아마 동작하는 부분의 사소한 차이인듯 보입니다. 
300번대가 redirection의 의미를 갖기 때문에 200번때 응답을 보낸다는 것에 조금 납득이 갔습니다.
