### ISSUE TITLE
Next js cors에러 질문이 있습니다. 

### ISSUE THREAD

**Issue by choi2021** [walking-sunset/wanted-pre-onboarding-qna-7th#13]
이번 과제에서 주어진 서버를 이용해 API를 연동하면서 생긴 cors에러를 어떻게 해결하면 좋을지 여쭤보고 싶습니다.
client: localhost:3000
server:localhost:4000

위와 같이 두개 다른 port로 연결했더니 cors에러가 발생했습니다.

![next cors에러](https://user-images.githubusercontent.com/80830981/201516131-d6b06d3f-afd1-40ad-80cb-16b72fd95f47.PNG)

해결하기 위해서 next.config.js에 rewrite를 이용해서 해당 api주소와 같은 param을 가질 경우 localhost:4000으로 우회하는 방법으로 우선은 해결해보려했습니다.

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  async rewrites() {
    return [
      {
           source: "/:path*",
	   destination: "http://localhost:4000/:path*",
      },
    ];
  },
};

module.exports = nextConfig;
```

하지만 이렇게 사용하게 되면 제가 사용하려 했던 login 파일 때문에 http://localhost:4000/login 로 post요청을 보낸 응답이 html파일로 받아지는 문제가 있었습니다. 

서버의 api를 피해서 파일들을 만들어서 routing을 해야할지 더 좋은 방법이 있는지 여쭤보고 싶습니다.

감사합니다.

**Comment by tesseractjh** [comment]
source를 기존에 사용하는 페이지 route와 겹치지 않게 변경해주면 되는 것 같습니다.
저는 source를 "/api/:path*" 이렇게 사용했습니다

```js
const nextConfig = {
  async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: 'http://localhost:4000/:path*',
      },
    ];
  },
};
```
```js
const result = axios.post('/api/login', { email, password });
```

**Comment by choi2021** [comment]
와.. 너무 감사합니다 ㅜㅜ
