### ISSUE TITLE
api 소스코드(december_and_company.zip) 안에 있는 generateDate.ts 를 수정해도 되나요??

### ISSUE THREAD

**Issue by YeonghunKO** [walking-sunset/wanted-pre-onboarding-qna-7th#14]
db.json에서 accounts를 불러올때 accounts안에 있는 값들을 살펴보면 user의 이름이 없습니다. 그리고 broker_id, status가 숫자코드로 저장이 되어있습니다.

그래서 generateData.ts를 수정해서 accounts에 user이름을 포함시키고 , brokder_id code와, status code에 해당하는 한글 값까지 포함시키려고 합니다. 

애초에 accounts를 json-server로 받아올때 필요한 모든 값이 들어있게끔 하려고 하거든요. 

**그래서 제목그대로 generateDate.ts를 수정해도 되는지 여쭈어 봅니다.**

아! 참고로 수정이 가능하다면, 사용하시는 로컬에서 별도의 작업을 하시지 않게끔 깃헙에 generateDate.ts에 수정이 반영된 코드를 올릴거구요,  그 코드로 배포까지 하려고 합니다.

**Comment by starkoora** [comment]
넵 제안해주신 방식으로 진행하셔도 될 것 같습니다
다만 이름은 포함시키되 상태 코드 같은 경우 한글 이름을 포함시키는 건 정보의 중복이라고 생각됩니다
