### ISSUE TITLE
1-1 과제 문의 드립니다.

### ISSUE THREAD

**Issue by tirhande** [walking-sunset/wanted-pre-onboarding-qna-7th#2]
안녕하세요.
프리온보딩 프론트엔드 7차 과제 관련하여 문의드립니다..

---- 
팀에서 생각한 원티드 프리온보딩 프론트엔드 선발 과제의 Best Pratice를 만들고 제출해주세요.
단위별로 Best Practice를 모아서 팀의 최종 결과물을 만들어내는 방식으로 진행해주세요.
----
라고 안내주셨는데

Best Practice 를 선정해서 하나로 모은후 하나의 리포에서 작업을 같이 해야할까요..?
그리고 실제 최종 결과물 코드를 사전과제때와 마찬가지로 데모 영상이나 배포 링크도 포함시켜야 하는건가요?

확인 부탁드립니다..

**Comment by walking-sunset** [comment]
- 실제 최종 결과물 코드를 사전과제때와 마찬가지로 데모 영상이나 배포 링크도 포함시켜야 하는건가요?
네, 맞습니다.

- Best Practice 를 선정해서 하나로 모은후 하나의 리포에서 작업을 같이 해야할까요..?
네, 맞습니다. 포인트마다 Best Practice를 토론해서 완성시키면서 최종적으로 완성된 하나의 결과물이 제출되면 됩니다.
