### ISSUE TITLE
과제 관련 문의 드립니다.

### ISSUE THREAD

**Issue by seungyeon-rr** [walking-sunset/wanted-pre-onboarding-qna-7th#3]
안녕하세요.
과제 제출 방식에서
```zsh
- 제출시에는 README가 필수적으로 작성되어야 하며, README에는 **최소한** 아래의 내용들이 포함되어야 합니다.
1. 팀장 및 팀원들의 이름 (팀마다 팀장을 선정 후 기록해주세요)
2. 해당 레포의 디렉토리 구조 및 코드 구조에 대한 자세한 설명
3. 과제의 결과물을 확인할 수 있는 배포된 URL의 링크와 확인 방법
4. 배포가 안되거나 불가능할 경우 기능을 상세히 확인할 수 있는 데모 영상등의 매체(video, gif, 외부 링크 등)
```
라고 쓰여 있는데, 2번의 '코드 구조에 대한 자세한 설명' 부분에 대해 문의 드립니다.

코드 구조에 대해 찾아보니 아래와 같은 레퍼런스를 발견했는데 이런 방식이 맞는지, 코드가 동작하는 방식이나 다른 추가 설명이 필요한 건지 답변 주시면 감사하겠습니다. :)
```
Electron
├── atom/ - C++ 소스 코드.
|   ├── app/ - 시스템 엔트리 코드.
|   ├── browser/ - 주 윈도우를 포함한 프론트엔드, UI, 그리고 메인 프로세스에 관련된
|   |   코드와 렌더러 및 웹 페이지 관리 관련 코드.
|   └── common/ - 메인과 렌더러 프로세스에서 모두 사용하는 코드, 몇가지 유틸리티
|       함수들이 포함되어 있고 node의 메시지 루프와 Chromium의 메시지 루프를 통합.
|       └── api/ - 공통 API 구현들, 기초 Electron 빌트-인 모듈들.
├── spec/ - 자동화 테스트.
├── electron.gyp - Electron의 빌드 규칙.
└── common.gypi - 컴파일러 설정 및 `node` 와 `breakpad` 등의 구성요소를 위한 빌드 규칙.
```

**Comment by walking-sunset** [comment]
안녕하세요, 레퍼런스 잘 찾아보신 것 같습니다 👍 

- 디렉토리 및 코드 구조에 대한 설명은 찾으신 레퍼런스와 유사하게 해주시면 됩니다.
- 코드에 대한 추가설명 같은 경우에는 `Best Practice를 찾아가는 과정에서 서로 많은 토론을 통해서 의견을 교환하고 소통하는법을 연습해주세요 그리고 중요하다고 생각되는 부분들은 왜 이것이 Best Practice라고 생각했는지에 대한 이유를 기술해주세요` 과제안내페이지에서 말씀드린 위 부분에 포함되는 부분에 포함이 될 것 같습니다~!

**Comment by walking-sunset** [comment]
찾으신 레퍼런스의 원문도 참고하시면 좋을 것 같습니다 :)
- https://www.electronjs.org/docs/latest/development/source-code-directory-structure
