### ISSUE TITLE
이번 과제에서 react-router-dom을 사용해도 되나요?

### ISSUE THREAD

**Issue by tesseractjh** [walking-sunset/wanted-pre-onboarding-qna-7th#6]
지난 투두리스트 과제에서는 사용할 수 있었는데, 이번 과제에는 명시되어 있지 않아서 혹시 사용할 수 있는지 궁금합니다.

**Comment by walking-sunset** [comment]
따로 명시해드리지 않았군요, react-router-dom은 항상 사용 가능합니다~!
