### ISSUE TITLE
환경 변수 값을 소스코드 주입을 막을 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by movie42** [walking-sunset/wanted-pre-onboarding-qna-7th#7]
안녕하세요. 
 
과제를 진행하면서 배포를 계속 진행해보게 되어 좋습니다. 
그런데 .env로 중요한 key값을 지정하면 결국 build를 할 때, 환경 변수가 소스 코드에 주입되서 웹에 노출 되는데요. 
이 방법을 backend를 통해서만 이 값을 가릴 수 있다고 하는데, 혹시 다른 방법으로 해결할 수 있을까요? 

  - build를 할 때 package.json script 값

    ```json
       {
           "script" : {
                "build": "GENERATE_SOURCEMAP=false react-scripts build",
                  }
       }
     ```

**Comment by walking-sunset** [comment]
안녕하세요, 일단 질문에 대해서 답변드리자면 결론적으로 불가능합니다.

- 말씀하신대로 build 될 때 포함되는게 기본 동작이며, 혹여나 제외하는 방법이 있다고 해도 환경변수가 제외된다고하면 필요한 변수가 결국 제대로 build 결과물이 포함되지 않는다는 의미이기에 제대로 동작이 되지 않습니다.

- 그리고 결국 client에서 발생하는 동작들은 맘만 먹으면 확인하고 접근할 수 있기에 중요한 정보들을 client에 노출시키는것은 좋지 않습니다. 그렇기에 기본적으로 상대적으로 외부와 격리할 수 있고 제어할 수 있는 server단에서 중요한 정보들을 처리하는게 기본적인 보안원칙으로 생각합니다.

- 결론은 build시에 환경변수를 제외하는 것은 불가능하며, client 단에서의 코드는 아무리 환경변수로 설정하고, 다른 방법을 통해서 감춘다고해도 결국 브라우저를 통해서 전체 소스코드에 접근이 가능하고 네트워크 요청을 통해서 사용자에게 보인다는 특징으로 인해 client단에서의 환경변수는 설정의 용이함 측면에 초점을 두고 사용하고 보안상 중요한 정보는 서버를 통해서 제어하는 것이 좋습니다.

**Comment by movie42** [comment]
네 감사합니다. 그럼 깃 헙 accesskey를 가릴 수 가 없군요... ㅜ

**Comment by walking-sunset** [comment]
네, 아쉽게도 완전히 가릴 수 있는 방법은 없습니다 :(
- 백엔드 서버가 있다면, 백엔드 서버에서 token을 이용한 GitHub API 호출을 진행하고 그 결과를 다시 프론트로 돌려주는 식으로 프론트단에서 환경변수를 제외 시킬 수 있습니다.
- 프론트로만 구현해야하는 상황에서는 완벽하진 않지만 그나마 보안조치를 취한다면 환경변수 세팅을 이용해서 1차적으로 GitHub에 노출되는 것을 방지, 빌드된 결과물에서 포함되어 있는 token에는 최대한 만료일자를 짧게 잡고, 권한을 진짜 필요한 권한만 부여하는 식의 조치를 취할 수 있을 것 같네요 :)
