### ISSUE TITLE
Week 2 - 1과제에서 api에 관한 질문입니다.

### ISSUE THREAD

**Issue by YeonghunKO** [walking-sunset/wanted-pre-onboarding-qna-7th#9]
혹시  api에 id parameter를 보낼 수 있나요? 노션 과제 페이지란에는 request query에 segment, fuelType 만 명시가 되어있더라구요. 

` https://preonboarding.platdev.net/api/cars?id=1` 이렇게 보내니 전체 자동차가 불러와지더라구요. 그래서 id parameter로 자동차를 불러올 수 있나 궁금해서 여쭈어 봅니다.

**Comment by walking-sunset** [comment]
과제에서 제공되는 API는 단일 API로 ID 파라미터는 구현되어 있지 않습니다~!
